### ISSUE TITLE
rename functions to remove unnecessary underscores

### ISSUE THREAD

**Issue by chfin** [DCMLab/DigitalMusicology.jl#12]
e.g. get_piece -> getpiece.

This seems to be more idiomatic in Julia.

**Comment by dharasim** [comment]
yes it is if it's still readable 👍 

gettheeggplant is a good counterexample

**Comment by chfin** [comment]
Doesn't Julia support unicode identifiers?
get:eggplant:(...)

**Comment by dharasim** [comment]
It works!

```julia
julia> get🍆() = :eggplant
get🍆 (generic function with 1 method)

julia> get🍆()
:eggplant
```

**Comment by chfin** [comment]
I think, this is mostly done.
