### ISSUE TITLE
Documenter Key Access

### ISSUE THREAD

**Issue by chfin** [DCMLab/DigitalMusicology.jl#3]
We now have documentation generation in Travis builds, but we need Travis to access the repo for pushing the doc to the gh-pages branch. @dharasim, could you generate a key pair with
```julia
julia> using Documenter
julia> Travis.genkeys("DigitalMusicology")
```
and add them to the repo and to Travis as described in the [Documenter.jl docs](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#SSH-Deploy-Keys-1)?
It seems like I don't have access to the settings of this repo.

**Comment by dharasim** [comment]
Ok, I did it and travis created the documentation.

How can the be viewed now? https://dcmlab.github.io/DigitalMusicology.jl/ does not seem to work at the moment. @chfin

**Comment by chfin** [comment]
The `gh-pages` branch does not have an `index.html` and the documentation is synchronized with versions, so there is a `latest` folder for the HEAD version:

https://dcmlab.github.io/DigitalMusicology.jl/latest/

We could either link directly to this url from the readme, or create an `index.html` in the `gh-pages` branch (given that it won't be overwritten by Documenter.jl) and link to this.

**Comment by chfin** [comment]
Added a badge with a link to `/latest`.
